# Generated by Django 3.2.13 on 2023-11-07 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0011_alter_comments_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author',
            new_name='user',
        ),
    ]
