# Generated by Django 3.2.13 on 2023-11-07 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0012_rename_author_author_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='author',
        ),
    ]
