# Generated by Django 3.2.13 on 2023-11-07 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0016_auto_20231107_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newsapp.author'),
        ),
    ]
