# Generated by Django 3.2.13 on 2023-11-07 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0018_alter_comments_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='author',
        ),
    ]
