# Generated by Django 3.2.13 on 2023-11-07 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0020_authorposts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorPosts',
        ),
    ]
