# Generated by Django 3.2.13 on 2023-11-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0021_delete_authorposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.BooleanField(default=False),
        ),
    ]
