# Generated by Django 3.2.13 on 2023-11-07 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0025_remove_comments_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
