# Generated by Django 3.2.13 on 2023-11-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0032_comments_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.EmailField(max_length=64),
        ),
    ]
